export const phrases = [
  "Your mic ic muted",
  "Let me share my screen with you",
  "The screen was frozen",
  "Your sound cuts in and out",
  "Can you hear me well?",
  "There is a bit of an echo on the line",
  "(Returning after leaving for water, toilet, etc.)",
  "(Sounds of animals such as cats, dogs, birds, etc.)",
  "Shall we begin?",
  "(Multiple people speaking at the same time with overlapping voices)",
  "Sorry, go ahead",
  "Sorry, I've got a bad connection",
  "Can you repeat what you said earlier please?",
  "Yes, I can see and hear you clearly",
  "How about now?",
  "Let me refresh my page",
  "No problem. Take your time",
  "Can you come closer to the mic, please?",
  "Sorry, my camera is not working today",
  "___ will join the call today",
  "You're back, ____",
  "We'll share the linke in the chat",
  "Let's circle back to that a bit later",
  "(Because of the background) you look like you're in another world!",
];
