export const phrases = [
  "Your mic ic muted",
  "Let me share my screen with you",
  "The screen was frozen",
  "Your sound cuts in and out",
  "Can you hear me well?",
  "There is a bit of an echo on the line",
  "(Returning after for toilet)",
  "(Sounds of pets)",
  "Shall we begin?",
  "(Overlapping voices)",
  "Sorry, go ahead",
  "Sorry, I've got a bad connection",
  "Can you repeat please?",
  "Yes, I can see and hear you clearly",
  "How about now?",
  "Let me refresh my page",
  "No problem. Take your time",
  "Can you come closer to the mic?",
  "Sorry, my camera is not working",
  "___ will join the call today",
  "You're back, ____",
  "We'll share the links in the chat",
  "(Using background effect)",
  "Just...(No Show)",
];
